### ISSUE TITLE
"Cannot operate on a closed database" error

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/logpyle#103]
Logpyle has broken backward compatibility recently:

```
 Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.11/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.11/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.11/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/grudge/grudge/test/test_mpi_communication.py", line 322, in <module>
    run_test_with_mpi_inner()
  File "/home/runner/work/grudge/grudge/test/test_mpi_communication.py", line 96, in run_test_with_mpi_inner
    f(actx, *args)
  File "/home/runner/work/grudge/grudge/test/test_mpi_communication.py", line 315, in _test_mpi_wave_op_entrypoint
    logger.info("Rank %d exiting", comm.rank)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.11/logging/__init__.py", line 1489, in info
    self._log(INFO, msg, args, **kwargs)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.11/site-packages/logpyle/__init__.py", line 662, in emit
    self.mgr.db_conn.execute(
sqlite3.ProgrammingError: Cannot operate on a closed databas
```
For example: https://github.com/inducer/grudge/actions/runs/4928343880/jobs/8806583617

**Comment by matthiasdiener** [comment]
Thanks! #104 should fix this. I'll release a new version as well.
