### ISSUE TITLE
Logging capture runs afoul of thread safety

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/logpyle#106]
```
Exception in thread Thread-1991 (_log_start_if_long):
Traceback (most recent call last):
  File "/home/andreas/pack/mambaforge/envs/ceesd/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/andreas/pack/mambaforge/envs/ceesd/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/andreas/src/pytools/pytools/__init__.py", line 2617, in _log_start_if_long
    self.logger.log(
  File "/home/andreas/pack/mambaforge/envs/ceesd/lib/python3.11/logging/__init__.py", line 1559, in log
    self._log(level, msg, args, **kwargs)
  File "/home/andreas/pack/mambaforge/envs/ceesd/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/home/andreas/pack/mambaforge/envs/ceesd/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/home/andreas/pack/mambaforge/envs/ceesd/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/home/andreas/pack/mambaforge/envs/ceesd/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/home/andreas/src/logpyle/logpyle/__init__.py", line 662, in emit
    self.mgr.db_conn.execute(
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139805741225792 and this is thread id 139798635280064.
```

**Comment by matthiasdiener** [comment]
I'm struggling to reproduce this, could you point me to a particular test that shows this error?

**Comment by inducer** [comment]
Yep, exactly.

**Comment by matthiasdiener** [comment]
This also affects warnings capture, and maybe other areas:

```python
import logpyle
from warnings import warn
from threading import Thread

def f():
    # Crashes with sqlite3.ProgrammingError
    warn("threaded")

logmgr = logpyle.LogManager("test.sqlite", "wo")

Thread(target=f).start()

logmgr.close()
```

**Comment by inducer** [comment]
I think a simple workaround (simpler than #107) is to add the warnings and log messages to a list (which is OK given that the GIL is being held in Python code) and dump them into the DB on `tick` and `close`.
