### ISSUE TITLE
'is_parallel' missing from constants

### ISSUE THREAD

**Issue by matthiasdiener** [illinois-ceesd/logpyle#15]
```bash
$ bin/runalyzer-gather summary.dat ../mirgecom/mylog.dat
Trouble with file '../mirgecom/mylog.dat'
Traceback (most recent call last):
  File "bin/runalyzer-gather", line 416, in <module>
    main()
  File "bin/runalyzer-gather", line 394, in main
    features, dbname_to_run_id = scan(fg, infiles)
  File "bin/runalyzer-gather", line 142, in scan
    logmgr = LogManager(dbname, "r")
  File "/Users/mdiener/Work/emirge/logpyle/logpyle/__init__.py", line 503, in __init__
    self._load()
  File "/Users/mdiener/Work/emirge/logpyle/logpyle/__init__.py", line 555, in _load
    self.is_parallel = self.constants["is_parallel"]
KeyError: 'is_parallel'
```

**Comment by inducer** [comment]
Cannot reproduce (on b2279c6).
```
$ runalyzer-gather sumamry.dat mylog.dat
Scanning...          [########################################] ETA ?
Importing...         [########################################] ETA ?
```

**Comment by matthiasdiener** [comment]
Can't reproduce it at the moment either, closing.
