### ISSUE TITLE
.plot with >2 parameters does not work

### ISSUE THREAD

**Issue by matthiasdiener** [illinois-ceesd/logpyle#23]
```
$ runalyzer -m summary.dat
Runalyzer running on Python 3.8.5 | packaged by conda-forge | (default, Sep 16 2020, 17:43:11)
[Clang 10.0.1 ]
Copyright (c) Andreas Kloeckner 2008
Run .help to see help for 'magic' commands
>>> .quantities
id | name    | unit | description                 | rank_aggregator
---+---------+------+-----------------------------+-----------------
7  | dt      | s    | Simulation Timestep         | None
9  | fifteen | None | None                        | None
5  | step    | 1    | Timesteps                   | None
2  | t_2step | s    | Step-to-step duration       | None
3  | t_cpu   | s    | Wall time                   | None
4  | t_log   | s    | Time spent updating the log | None
6  | t_sim   | s    | Simulation Time             | None
1  | t_step  | s    | Time step duration          | None
8  | t_vis   | s    | Time spent visualizing      | None
>>> .plot select $step, $t_step, $t_cpu
Traceback (most recent call last):
  File "/Users/mdiener/Work/emirge/logpyle/logpyle/runalyzer.py", line 305, in push
    self.execute_magic(cmdline)
  File "/Users/mdiener/Work/emirge/logpyle/logpyle/runalyzer.py", line 373, in execute_magic
    self.db.plot_cursor(cursor, columnnames)
  File "/Users/mdiener/Work/emirge/logpyle/logpyle/runalyzer.py", line 120, in plot_cursor
    do_plot(x, y, rest)
  File "/Users/mdiener/Work/emirge/logpyle/logpyle/runalyzer.py", line 115, in do_plot
    plot(x, y, hold=True, *args, **my_kwargs)
  File "/Users/mdiener/miniforge3/envs/ceesd/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2840, in plot
    return gca().plot(
  File "/Users/mdiener/miniforge3/envs/ceesd/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1743, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/Users/mdiener/miniforge3/envs/ceesd/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 273, in __call__
    yield from self._plot_args(this, kwargs)
  File "/Users/mdiener/miniforge3/envs/ceesd/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 418, in _plot_args
    return [func(x[:, j % ncx], y[:, j % ncy], kw, kwargs)
  File "/Users/mdiener/miniforge3/envs/ceesd/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 418, in <listcomp>
    return [func(x[:, j % ncx], y[:, j % ncy], kw, kwargs)
  File "/Users/mdiener/miniforge3/envs/ceesd/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 312, in _makeline
    seg = mlines.Line2D(x, y, **kw)
  File "/Users/mdiener/miniforge3/envs/ceesd/lib/python3.8/site-packages/matplotlib/lines.py", line 390, in __init__
    self.update(kwargs)
  File "/Users/mdiener/miniforge3/envs/ceesd/lib/python3.8/site-packages/matplotlib/artist.py", line 996, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'Line2D' object has no property 'hold'
```

**Comment by inducer** [comment]
What type of plot would you expect in this situation?

**Comment by matthiasdiener** [comment]
No idea, but there seems to be some kind of support for it:

https://github.com/illinois-ceesd/logpyle/blob/d42edc813a140a638828170bc8737f5d528fda69/logpyle/runalyzer.py#L80-L110

Fixing the matplotlib errors results in some ...strange... graphics.

**Comment by inducer** [comment]
OIC. I guess it's using the remaining row properties to plot different lines. That means you need to sort by those remaining properties, otherwise you'll understandably get garbage.
